version: '3.2'

services:
  jenkins:
    build:
      context: Jenkins-image/
    image: jenkins/local
    restart: always
    container_name: jenkins-server
    volumes:
      - type: bind
        source: ./jenkins_home
        target: /var/jenkins_home
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /usr/bin/docker
        target: /usr/bin/docker
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - net-jenkins

networks:
  net-jenkins:
